### ISSUE TITLE
bug: regex anti pattern

### ISSUE THREAD

**Issue by jayceslesar** [ibis-project/ibis-bigquery#110]
Hey all, can take a stab to fix this but this seems like an anti pattern here to wrap a regex that could contain a bunch of specific regexes into a literal string in [this](https://github.com/ibis-project/ibis-bigquery/blob/main/ibis_bigquery/compiler.py#L153) line. Currently giving me an issue where I am explicitly building my strings for a `.re_search` call with escape characters and groups.

Essentially I am trying to query on a column value that has `(` and `)` in it that is in the column field with name `some_message_((&some_signal)))`
```SQL
SELECT *
FROM `my_project.my_dataset.my_table`
WHERE REGEXP_CONTAINS(`field`, '(some_message_\\(\\(&some_signal\\)\\))')
```
is the bigquery query I can write and it works totally fine in the console (and the regex I build in python also works fine), but when I pass the regex into ibis, which is everything in the right string in the regexp_contains call,
it spits out a query like:
```SQL
SELECT *
FROM `my_project.my_dataset.my_table`
WHERE REGEXP_CONTAINS(`field`, r'(some_message_\\(\\(&some_signal\\)\\))')
```
which is not helpful.

**Comment by tswast** [comment]
Not sure if this is an anti pattern.

Per https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#literals

> Raw string | `R"abc+"r'''abc+'''R"""abc+"""r'f\(abc,(.*),def\)'` | Quoted or triple-quoted literals that have the raw string literal prefix (r or R) are interpreted as raw/regex strings.Backslash characters (\) do not act as escape characters. If a backslash followed by another character occurs inside the string literal, both characters are preserved. A raw string cannot end with an odd number of backslashes.Raw strings are useful for constructing regular expressions.

**Comment by tswast** [comment]
Are you finding that ibis is basically double-escaping these characters?

**Comment by jayceslesar** [comment]
I explicitly build the string `'(some_message_\\(\\(&some_signal\\)\\))'` and then pass it into the ibis re_search and when I compile the query ibis creates it puts an "r" infront of the string, which doesn't match any strings in the column I am searching for. Maybe should be a flag in that function to ensure the user knows the string they are passing into ibis will be interpreted as a raw string vs not?
