### ISSUE TITLE
enable usage of BigQuery backend through `ibis`

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis-bigquery#34]
I think the first usage example in the [readme](https://github.com/ibis-project/ibis-bigquery#connecting-to-bigquery) (using BigQuery backend through `import ibis`) doesn't work quite yet (I think this would require entrypoints being set up in this repo)

**Comment by tswast** [comment]
This is turning out to be harder than I expected. I added the entry points, in #38 but I am hitting circular dependency issues with the current way that backends are discovered.

**Comment by tswast** [comment]
I figured it out. Whereever `import ibis_bigquery` appears, `import ibis` must appear first. Otherwise, we get circular dependencies.
