### ISSUE TITLE
Add STARTS_WITH and ENDS_WITH

### ISSUE THREAD

**Issue by saschahofmann** [ibis-project/ibis-bigquery#61]
We registered the two functions in our project and could make a quick PR to enable them in this repo. Let me know if that's something you're interested!

**Comment by tswast** [comment]
Cool! Do the exist already as operators in the core Ibis library? If not, let's add them there first.

**Comment by saschahofmann** [comment]
Ah they do not but I guess it's standard SQL functionality. Will have a look on how that's going to work.

**Comment by saschahofmann** [comment]
Closing in favor of ibis-project/ibis#2790
