### ISSUE TITLE
test suite failing against ibis-project/ibis master branch

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis-bigquery#90]
```
ImportError while loading conftest '/Users/swast/src/ibis-bigquery/tests/system/conftest.py'.
tests/system/conftest.py:3: in <module>
    import ibis  # noqa: F401
../ibis/ibis/__init__.py:6: in <module>
    import ibis.backends.pandas
../ibis/ibis/backends/pandas/__init__.py:2: in <module>
    from ibis.backends.base import BaseBackend
../ibis/ibis/backends/base/__init__.py:5: in <module>
    import ibis.expr.operations as ops
../ibis/ibis/expr/operations.py:10: in <module>
    from cached_property import cached_property
E   ModuleNotFoundError: No module named 'cached_property'
```

**Comment by tswast** [comment]
`cached_property` is a new dependency, added in https://github.com/ibis-project/ibis/pull/2805

**Comment by tswast** [comment]
Once that's added, test suite fails with

```
ImportError while loading conftest '/Users/swast/src/ibis-bigquery/tests/system/conftest.py'.
tests/system/conftest.py:7: in <module>
    import ibis_bigquery
ibis_bigquery/__init__.py:11: in <module>
    from .client import BigQueryClient, BigQueryDatabase, BigQueryQuery, BigQueryTable
ibis_bigquery/client.py:24: in <module>
    from ibis.client import Database, Query, SQLClient
E   ModuleNotFoundError: No module named 'ibis.client'
```

**Comment by tswast** [comment]
Database, SQLClient moved: https://github.com/ibis-project/ibis/pull/2810

Query deleted: https://github.com/ibis-project/ibis/pull/2789

**Comment by tswast** [comment]
BaseExprTranslator removed / renamed in https://github.com/ibis-project/ibis/pull/2746

**Comment by tswast** [comment]
QueryBuilder removed in https://github.com/ibis-project/ibis/pull/2818 (Renamed to Compiler?)

**Comment by tswast** [comment]
I had hopes of having at least a few versions of `ibis-bigquery` compatible with both recent 1.x and 2.x `ibis-framework` packages, but with these significant refactorings I wonder how realistic that is?

**Comment by tswast** [comment]
@datapythonista I think I'm going to need some help on this. There have been quite a few changes since I last set aside some time to work on this.

**Comment by datapythonista** [comment]
Sure, happy to help. There is a failing test I don't understand, but other than that this OmniSciDB PR is what needs to be done: https://github.com/omnisci/ibis-omniscidb/pull/39

**Comment by datapythonista** [comment]
There are many changes, but the main thing is that QueryBuilder is now Compiler, and most attributes spread in all the compiler classes are now there. So, with some exceptions, most other classes can be deleted (they don't have attributes to overwrite).

**Comment by tswast** [comment]
It's becoming infeasible to support 1.x and 2.x in the same branch. I propose dropping the tests against 2.x HEAD from our master branch and creating a `v2` branch that only supports Ibis 2.x.

**Comment by tswast** [comment]
I think I've finally made the last of the necessary changes in https://github.com/ibis-project/ibis-bigquery/pull/93
